# -*- coding: utf-8 -*-
import engine

PATH = "CSS 进阶知识点系统梳理_优化版.md"

content_map = {
    "### 2.1 标准盒模型 vs IE 盒模型": (
        "明确元素 width/height 到底包含哪些部分，是精确还原设计稿与排查布局错位的前提。",
        "标准盒模型 content-box 的 width 仅指内容区，实际占位需再加 padding 与 border；IE 盒模型 border-box 的 width 已包含内容+padding+border，内容区被压缩。box-sizing 属性决定采用哪种模型。",
        ["全局推荐 *{box-sizing:border-box}，使设定宽度即实际宽度",
         "content-box 下设宽后内容+padding+border 会超出预期宽度",
         "border-box 下增大 padding/border 不改变总宽，只挤占内容区",
         "表单元素（input/select）默认盒模型不一致，需显式统一",
         "面试常考两种模型区别与 box-sizing 取值"],
    ),
    "### 4.1 什么是 BFC": (
        "理解 BFC（块级格式化上下文）是掌握 margin 折叠、清除浮动、自适应两栏等布局问题的钥匙。",
        "BFC 是一个独立的块级渲染区域，内部盒子按块格式化规则垂直排列且对外隔离——内部浮动不会影响外部，外部浮动也不会侵入其内部。",
        ["BFC 是封闭的布局上下文，内部布局不影响外部",
         "同一 BFC 内相邻块级盒子的垂直 margin 会发生折叠",
         "计算 BFC 高度时会包含其中的浮动元素",
         "常与 IFC（行内格式化上下文）对比理解",
         "面试常以“解决 margin 塌陷/清除浮动”引出"],
    ),
    "### 4.2 触发条件": (
        "知道如何主动创建 BFC，才能用它解决具体布局问题。",
        "满足特定 CSS 条件时元素会生成新 BFC，如 overflow 非 visible、浮动、绝对/固定定位、display 为 flex/grid/inline-block 等。",
        ["overflow:hidden/auto/scroll 最常用，但可能裁剪溢出内容",
         "display:flex/grid 容器及其直接子项会形成 BFC",
         "float 非 none、position:absolute/fixed 也会触发",
         "display:flow-root 是专为创建 BFC 设计、无副作用的属性",
         "现代布局优先用 flex/grid 而非 overflow hack"],
    ),
    "### 5.1 容器属性": (
        "Flex 容器属性决定子项整体的排列方向、换行与对齐，是一维布局的“主轴控制”。",
        "Flex 容器存在主轴（main axis，由 flex-direction 决定方向）与交叉轴（cross axis）。justify-content 控制主轴分布，align-items 控制交叉轴对齐，flex-wrap 控制是否换行。",
        ["flex-direction 决定主轴方向（row/column）",
         "justify-content 管主轴（center 居中、space-between 两端）",
         "align-items 管交叉轴（center 居中、stretch 拉伸）",
         "多行时 align-content 控制行与行之间的分布",
         "容器设 display:flex 后，子项 float/clear/vertical-align 失效"],
    ),
    "### 5.2 子项属性": (
        "子项属性在容器规则基础上对单个元素做精细控制（放大、缩小、排序、单独对齐）。",
        "flex-grow 分配主轴剩余空间，flex-shrink 在空间不足时收缩，flex-basis 设定初始主轴尺寸；最终尺寸 = basis + grow/shrink 调整。order 改变视觉顺序，align-self 覆盖容器 align-items。",
        ["flex:1 = flex:1 1 0%，按剩余空间比例平分",
         "flex-basis 优先级高于 width（主轴为 row 时）",
         "flex-shrink:0 防止被压缩，用于固定宽栏",
         "order 仅改视觉顺序，不影响 DOM 与可访问性顺序",
         "align-self 可对单个子项单独设置交叉轴对齐"],
    ),
    "### 6.1 容器属性": (
        "Grid 容器属性定义网格的行列轨道、间距与整体对齐，是二维布局的骨架。",
        "display:grid 将容器划分为行轨道（grid-template-rows）和列轨道（grid-template-columns）组成的二维网格；fr 表示剩余空间比例；gap 统一设置间距。",
        ["grid-template-columns/rows 用长度、fr 或 repeat() 定义轨道",
         "repeat(3,1fr) 等价于 1fr 1fr 1fr",
         "fr 是剩余空间比例，可配合固定值做混合布局",
         "justify/align-items 控制单元格内对齐，content 系列控制整个网格分布",
         "响应式可用 repeat(auto-fill/auto-fit, minmax())"],
    ),
    "### 6.2 子项属性": (
        "Grid 子项属性让单个元素跨越指定行列或占据命名区域，实现复杂版式。",
        "grid-column/grid-row 用“起始线/结束线”指定子项占据的网格区间（线编号从 1 开始）；grid-area 可引用 grid-template-areas 定义的命名区域；justify-self/align-self 单独控制对齐。",
        ["grid-column:1/3 表示跨第1到第3列线（占2列）",
         "线编号可用负数表示从末尾倒数",
         "grid-area 四值简写：row-start/col-start/row-end/col-end",
         "命名区域法（grid-template-areas）可读性最好",
         "justify-self/align-self 覆盖容器对单个子项的对齐"],
    ),
    "### 7.1 媒体查询": (
        "媒体查询是响应式设计的开关，按设备视口/特性加载不同样式。",
        "@media 在满足条件（min/max-width、orientation、resolution 等）时应用内部样式块；移动端优先用 min-width 由小到大增强，PC 优先用 max-width 由大到小降级。",
        ["移动端优先推荐 min-width，避免大屏冗余覆盖",
         "断点应按内容而非具体设备设定（如 768/1024）",
         "常用条件 width、height、orientation、prefers-reduced-motion",
         "可组合多个条件用 and / ,（或）",
         "媒体查询只切换样式、无法改变 DOM 结构"],
    ),
    "### 7.2 视口设置": (
        "viewport meta 标签控制移动端页面按设备宽度渲染，是响应式的前提。",
        "默认移动浏览器以约 980px 的“布局视口”渲染再缩放；width=device-width 让布局视口等于设备宽度，initial-scale=1 设初始缩放为 1，从而避免页面被缩扁。",
        ["移动端必须加 <meta name=viewport content=width=device-width,initial-scale=1>",
         "width=device-width 使 CSS 像素映射设备宽度",
         "maximum-scale/user-scalable 可禁缩放（影响可访问性，慎用）",
         "需配合 rem/vw 方案才能实现等比适配",
         "缺失它会让媒体查询基于桌面视口，布局错乱"],
    ),
    "### 7.3 相对单位": (
        "相对单位让尺寸随上下文（父/根/视口）伸缩，是流式布局与等比适配的基础。",
        "% 相对父元素；em 相对自身 font-size（易层层放大）；rem 相对根元素 html 的 font-size（可控）；vw/vh 相对视口宽高；vmin/vmax 取视口较小/较大边。",
        ["rem 适配：动态设 html font-size，全站用 rem 实现等比缩放",
         "em 受父级 font-size 影响，嵌套需谨慎",
         "vw/vh 适合全屏与流体字号，但极端宽屏需 clamp 限制",
         "vmin/vmax 用于需兼顾横竖屏的场景",
         "与媒体查询/容器查询配合覆盖不同断点"],
    ),
    "### 8.1 transition 过渡": (
        "transition 让属性在状态变化时平滑过渡，用于 hover、展开等轻量动效。",
        "transition 监听指定属性从旧值到新值的变化，在 duration 内按 timing-function 插值；仅在属性“值改变”时触发，首次渲染不生效。",
        ["语法：transition: 属性 时长 缓动 延迟",
         "可写 all 或指定属性（推荐指定，性能更可控）",
         "仅对可插值属性生效（颜色、transform、尺寸），display 不可过渡",
         "回退状态用 opacity+visibility 代替 display:none",
         "配合 will-change 可提前提升合成层（勿滥用）"],
    ),
    "### 8.2 animation 关键帧动画": (
        "animation + @keyframes 实现多关键帧、可循环的复杂动画，比 transition 更自由。",
        "@keyframes 定义动画在 0%→100% 各阶段的样式，animation 将其绑定到元素并控制时长、缓动、次数、方向、填充模式；浏览器在每帧计算插值并渲染。",
        ["@keyframes 用 from/to 或百分比定义关键帧",
         "animation 简写：name duration timing delay iteration direction fill-mode",
         "forwards 让动画结束后保持终态",
         "infinite 无限循环，alternate 来回播放",
         "优先动画 transform/opacity 以走合成层、避免重排重绘"],
    ),
    "### 9.1 优先级计算": (
        "掌握优先级才能预判哪条样式生效，快速定位“样式不生效”类问题。",
        "CSS 按（行内, ID, 类/属性/伪类, 标签/伪元素）四元组权重比较，高位相同才比低位；!important 可压过一切（除更高优先级 !important）；同权重后写覆盖先写。",
        ["权重顺序：!important > 行内(1000) > ID(100) > 类(10) > 标签(1) > 通配符(0)",
         "权重是逐位比较而非简单相加，10 个类胜不了 1 个 ID",
         "内联 style 优先级极高、难覆盖",
         "避免过度嵌套导致优先级失控",
         "调试用 DevTools 的“计算样式”查看命中规则"],
    ),
    "### 10.1 CSS 自定义属性（变量）": (
        "CSS 变量实现一处定义、多处复用，是主题切换与设计 token 化的基础。",
        "自定义属性以 --name 声明（常放 :root 作为全局），用 var(--name[, fallback]) 引用；变量可继承，可被 JS 通过 style.setProperty 动态修改，从而实时换肤。",
        ["声明：--primary:#3498db，使用：color:var(--primary)",
         ":root 声明的变量全局可用",
         "var() 第二个参数为回退值（变量未定义时生效）",
         "JS 改主题：document.documentElement.style.setProperty('--primary', x)",
         "结合 calc() 可做数学运算；变量区分大小写"],
    ),
    "### 10.2 现代 CSS 特性": (
        "现代 CSS 特性减少 JS 依赖，用声明式方式解决比例、流体排版、毛玻璃等常见需求。",
        "aspect-ratio 固定宽高比；clamp(min,pref,max) 在上下限间选取首选值（流体排版）；min()/max() 取极值；:is()/:where() 分组选择器（:where 权重为 0）；backdrop-filter 对元素后方做模糊；subgrid 让嵌套网格继承父轨道。",
        ["clamp(14px,2vw,20px) 实现随视口缩放但有界的字号",
         "aspect-ratio 替代 padding-top hack 做响应式盒子",
         "backdrop-filter:blur() 实现毛玻璃（注意性能与背景要求）",
         ":where() 权重为 0，适合写重置样式",
         "subgrid 需父网格支持，用于对齐嵌套内容；这些特性需关注兼容并加回退"],
    ),
}

new_lines, added = engine.expand(
    PATH,
    content_map,
    add_top_note=True,
    add_summary=False,
    summary_text="",
)
print("CSS done. new_lines=%d added_blocks=%d" % (new_lines, added))
