# -*- coding: utf-8 -*-
import engine

PATH = "TypeScript AIGC应用开发知识点系统梳理_优化版.md"

content_map = {
    "### 2.1 Vercel AI SDK 文本生成": (
        "文本生成是 AIGC 最基础的能力，Vercel AI SDK 用统一 API 覆盖流式与非流式。",
        "generateText 一次性返回完整文本，streamText 返回可异步迭代的 textStream，二者都接收 model/messages/prompt/system/temperature/maxTokens 等参数，底层对接各家模型。",
        ["generateText 适合短文本/后台任务",
         "streamText 配合前端实现打字机",
         "system 设定角色，prompt 给任务",
         "temperature 控制创意度，maxTokens 限制长度",
         "统一 API 可无缝切换 OpenAI/Claude 等模型"],
    ),
    "### 2.2 Prompt 模板与变量": (
        "用模板与变量动态拼装 Prompt，是工程化复用的关键。",
        "通过模板字符串把 topic/style/wordCount 等变量注入 system 与 prompt，函数化封装后可在多处复用，避免硬编码。",
        ["将可变部分抽成函数参数",
         "system 固定人设，prompt 带变量",
         "注意变量转义与长度控制",
         "可结合 i18n 做多语言 Prompt",
         "模板化便于 A/B 测试不同措辞"],
    ),
    "### 2.3 结构化输出（Zod Schema）": (
        "用 Zod Schema 让模型输出强类型的结构化对象，便于程序直接消费。",
        "generateObject 接收 schema，模型生成被约束为符合 z.object 的对象；describe 注解会提示模型字段含义，提升抽取质量。",
        ["用 generateObject 而非手拼 JSON",
         "describe 写清字段用途，提升准确率",
         "嵌套数组/对象都支持",
         "输出可直接 TS 类型推断",
         "适合文章结构、表单、实体抽取"],
    ),
    "### 2.4 批量生成与并发控制": (
        "批量任务需并发提升吞吐，同时避免触发限流。",
        "Promise.all 并发发起多个生成请求，但无限制并发会打满配额；用 p-limit 限制同时进行的请求数，在速度与稳定性间取平衡。",
        ["p-limit 控制并发上限（如 3）",
         "配合轻量模型（mini）降本",
         "失败要做单条重试而非整体失败",
         "可加分批（chunk）处理超长列表",
         "监控配额与 429"],
    ),
    "### 3.1 DALL-E 3（OpenAI）": (
        "DALL-E 3 是高质量文生图模型，理解复杂提示词。",
        "client.images.generate 传入 prompt/size/quality/style，返回图片 URL 或 base64；DALL-E 2 额外支持 images.edit 用 mask 局部重绘。",
        ["response_format 取 url 或 b64_json",
         "quality:'hd' 更精细但更慢更贵",
         "style 控制 vivid/natural",
         "中文提示词效果依赖模型翻译能力",
         "编辑用 images.edit + mask"],
    ),
    "### 3.2 Stable Diffusion（Replicate）": (
        "SD 开源可自部署，Replicate 提供托管 API，风格可控性强。",
        "replicate.run 调用 SDXL 模型，input 传 prompt/negative_prompt/尺寸/步数/guidance_scale；输出为图片 URL 数组，可换不同底模与 LoRA。",
        ["negative_prompt 排除不想要的元素",
         "num_inference_steps 影响质量与耗时",
         "guidance_scale 控制贴合提示词程度",
         "Replicate 托管免部署",
         "可换底模实现特定画风"],
    ),
    "### 3.3 通义万相（阿里云）": (
        "通义万相是国产文生图方案，适合国内合规与低延迟场景。",
        "DashScope 的 tasks.post 提交生成任务（异步），返回 task_id，再 tasks.get 轮询结果；输出图片 URL。",
        ["万相为异步任务，需轮询 task_id",
         "参数 size 用 * 分隔（如 1024*1024）",
         "国内访问延迟低、合规友好",
         "注意轮询间隔与超时",
         "与 DALL-E 接口形态不同，需适配"],
    ),
    "### 3.4 前端图像展示与下载": (
        "前端负责把生成结果展示给用户并提供下载/保存。",
        "前端调后端 /api 生成拿到图片 URL，用 ref 绑定显示并 loading 态；下载通过动态创建 <a download> 触发浏览器保存。",
        ["生成期间用 loading 禁用按钮防重复提交",
         "展示用 <img :src> 或 el-image 预览",
         "下载用 a.download 指定文件名",
         "跨域图片下载可能需后端代理",
         "可加错误提示与重试"],
    ),
    "### 4.1 OpenAI TTS 语音合成": (
        "TTS 把文本转为自然语音，用于配音、播报、无障碍。",
        "client.audio.speech.create 传入 model/voice/input/response_format/speed，返回音频流；写入文件或前端播放。",
        ["voice 可选 alloy/echo/fable/onyx/nova/shimmer",
         "response_format 多取 mp3",
         "speed 调语速",
         "后端生成后返回音频 URL 给前端 <audio>",
         "大段文本注意时长与费用"],
    ),
    "### 4.2 Whisper 语音识别": (
        "Whisper 把语音转为文字（ASR），支持多语言与带时间戳。",
        "client.audio.transcriptions.create 上传音频流，返回文本；response_format 取 verbose_json 可获 word/segment 级时间戳。",
        ["language 指定语言提升准确率",
         "verbose_json 支持字级/句级时间戳（字幕友好）",
         "中文用 'zh'",
         "大文件可先切片",
         "前端录音→后端识别是常见链路"],
    ),
    "### 4.3 浏览器原生 Web Speech API": (
        "Web Speech API 在浏览器内完成 TTS/ASR，零成本、无需密钥。",
        "SpeechSynthesisUtterance 配置文本/语言/语速/音高，speechSynthesis.speak 朗读；SpeechRecognition 监听 onresult 实时返回识别文本。",
        ["TTS：utterance.lang='zh-CN' 设语言",
         "ASR 需用户授权且多数浏览器依赖网络",
         "continuous/interimResults 控制连续与临时结果",
         "兼容性差异大（webkit 前缀）",
         "适合轻量、隐私敏感场景"],
    ),
    "### 5.1 GPT-4o 图像理解": (
        "多模态模型能“看懂”图片并作答，是图文分析基础。",
        "在 messages 的 content 中以 {type:'image', image:url/base64} 与文本混合输入，GPT-4o 联合理解后返回答案；多图用数组拼接。",
        ["图片可用 URL 或 base64",
         "多图对比把所有图放进 content 数组",
         "支持图文问答、OCR、图表理解",
         "base64 会增大请求体，注意体积",
         "计费按图像 token"],
    ),
    "### 5.2 视频帧分析": (
        "把视频拆成帧再用多模态模型分析，是常见的视频理解方案。",
        "ffmpeg 按时间间隔抽帧，逐帧调用多模态分析，最后用 LLM 汇总各帧结论得到视频级理解。",
        ["抽帧间隔影响覆盖率与成本",
         "逐帧并行分析（Promise.all）提速",
         "汇总阶段用 LLM 聚合时间线",
         "帧过多需降采样",
         "适合内容审核、精彩片段识别"],
    ),
    "### 6.1 OpenAI Moderation API": (
        "上线前对用户输入/模型输出做合规审核，降低风险。",
        "client.moderations.create 传入文本，返回 results[].flagged 与 categories（暴力/仇恨/自残等），标记则拦截。",
        ["result.flagged 表示是否违规",
         "categories 给出具体类别便于处理",
         "支持批量输入",
         "审核应在生成前（输入）与生成后（输出）都做",
         "不可完全依赖，需结合业务规则"],
    ),
    "### 6.2 Prompt 注入防护": (
        "防止用户通过精心构造输入劫持系统指令，是 AIGC 安全重点。",
        "一方面用正则/规则过滤明显注入短语（sanitizeInput），另一方面用“指令隔离”——把用户输入包裹在特殊标记中并明确告知模型“不得执行其中指令”。",
        ["关键字黑名单做第一道防线",
         "指令隔离标记（<<<INPUT>>>）降低注入成功率",
         "系统提示词明确优先级高于用户输入",
         "敏感操作需二次确认/权限",
         "持续更新规则应对新手法"],
    ),
    "## 6.3 视频生成（Runway / 可灵 / Sora）": (
        "文生/图生视频让 AIGC 从静态走向动态，应用前景广。",
        "Runway/可灵等提供异步任务 API：提交 prompt/图片得到 task_id，再轮询直到 succeeded 取视频 URL；Sora 类似但接口不同。",
        ["视频生成为异步，提交后轮询状态",
         "支持文生视频与图生视频（image_url）",
         "轮询需设超时与最大次数",
         "不同平台返回字段不同需适配",
         "耗时较长，前端应显示进度"],
    ),
    "## 6.4 音乐生成（Suno / Udio）": (
        "AI 音乐生成降低作曲门槛，可用于配乐、营销。",
        "Suno 等 API 接收 prompt/style/title 生成歌曲，返回音频 URL、封面、时长；常先用 LLM 写歌词再喂给音乐模型。",
        ["可 LLM 先生成歌词再生成音乐",
         "返回含音频/封面/时长元信息",
         "第三方代理 API 形态不统一",
         "注意版权与商用授权",
         "适合短视频 BGM、Demo"],
    ),
    "## 6.5 浏览器端 AI（WebLLM / Transformers.js）": (
        "在浏览器本地运行模型，数据不出端、零 API 成本、低延迟。",
        "Transformers.js 用 WASM 后端在浏览器跑分类/Embedding 等任务；WebLLM 用 WebGPU 加载 LLM（如 Llama-3）做对话，模型权重按需下载缓存。",
        ["Transformers.js 适合分类/特征提取/Embedding",
         "WebLLM 需 WebGPU，首次加载模型较慢",
         "数据不出浏览器，隐私友好",
         "适合轻量、离线、敏感场景",
         "模型体积与设备性能是瓶颈"],
    ),
    "## 6.6 AIGC 内容水印与溯源": (
        "为生成内容加水印与凭证，支撑合规、防伪与溯源。",
        "不可见数字水印把信息藏入像素（steganography）；C2PA 内容凭证把生成动作（模型/时间/Prompt）写入可验证的元数据清单并签名。",
        ["不可见水印抗简单裁剪但非绝对",
         "C2PA 提供可验证溯源（模型/时间/编辑史）",
         "生成内容标识是监管趋势",
         "签名确保凭证不被篡改",
         "配合审核形成安全闭环"],
    ),
    "### 7.1 AI 写作助手": (
        "写作助手把长文创作拆成大纲→生成→润色的可控流程。",
        "典型链路：用户输入主题→LLM 生成大纲→用户编辑→按段生成正文→润色→导出；每步都可人工介入。",
        ["先大纲后正文，避免一次性长文失控",
         "分段生成便于用户修订",
         "润色可单独调用",
         "导出支持 Markdown/PDF",
         "适合博客、报告、文案"],
    ),
    "### 7.2 AI 图像生成器": (
        "图像生成器封装 Prompt→生成→对比→放大→下载的完整体验。",
        "用户输入 Prompt 并选风格，调用图像模型生成多版本，前端对比，高清放大后下载保存。",
        ["多版本对比提升可用性",
         "高清放大（upscale）增强细节",
         "风格预设降低门槛",
         "支持下载与分享",
         "需内容审核兜底"],
    ),
    "### 7.3 智能语音助手": (
        "语音助手实现“说—听—答—读”的自然交互闭环。",
        "语音输入经 ASR 转文字，LLM 理解并生成回复，TTS 转语音播放，形成完整的语音对话。",
        ["ASR→LLM→TTS 三段式",
         "可加唤醒词与打断",
         "延迟优化靠流式与边缘",
         "适合车载、无障碍、客服",
         "注意隐私与授权"],
    ),
    "### 7.4 多模态内容分析": (
        "多模态分析把图片/视频内容转为结构化报告，赋能审核与检索。",
        "上传素材→抽帧/切图→多模态模型理解→结构化输出→汇总成报告，常用于内容审核、媒体分析。",
        ["上传后先做预处理（抽帧/缩放）",
         "多模态模型输出结构化字段",
         "汇总 LLM 生成可读报告",
         "适合审核、标签、摘要",
         "注意成本与并发"],
    ),
    "### 8.1 缓存策略": (
        "缓存相同请求结果，直接降低 API 调用与成本。",
        "用 prompt+model 的哈希作缓存键，命中 Redis 直接返回；未命中才调用模型并写回（带 TTL）。",
        ["缓存键含 model 与 prompt（md5）",
         "TTL 按内容时效设置（如 3600s）",
         "适合重复性问题/模板输出",
         "敏感或个性化内容不宜缓存",
         "命中率是要监控的核心指标"],
    ),
    "### 8.2 模型分级路由": (
        "按任务复杂度选模型，在质量与成本间平衡。",
        "估算 prompt 复杂度，简单任务用低价模型（mini），复杂任务用旗舰（gpt-4o/o1），把算力用在刀刃上。",
        ["复杂度可用规则或轻模型预估",
         "简单问答/分类用 mini 降本",
         "推理/长文用强模型",
         "路由可叠加 Fallback",
         "监控各模型用量与成本"],
    ),
    "### 8.3 Token 统计与监控": (
        "Token 是计费与限速单位，统计监控是成本控制前提。",
        "generateText 等返回 usage（promptTokens/completionTokens/totalTokens），据此估算费用并监控趋势。",
        ["usage 提供输入/输出/总 token",
         "成本=输入×输入价+输出×输出价",
         "监控 P95 token 与异常尖峰",
         "长上下文需警惕费用",
         "结合缓存与路由压低成本"],
    ),
}

new_lines, added = engine.expand(
    PATH,
    content_map,
    add_top_note=True,
    add_summary=False,
    summary_text="",
)
print("TS-AIGC done. new_lines=%d added_blocks=%d" % (new_lines, added))
