# -*- coding: utf-8 -*-
import engine

PATH = "TypeScript AI Agent开发知识点系统梳理_优化版.md"

content_map = {
    "### 2.1 核心概念": (
        "理解 Vercel AI SDK 的核心 API 划分，是搭建全栈 AI 应用的基础。",
        "SDK 统一封装了不同模型厂商的调用差异：后端用 streamText/streamObject/generateText 生成，前端用 useChat/useCompletion 钩子消费，tool/embed 提供工具与向量能力。",
        ["streamText 流式文本，generateText 非流式，streamObject 流式结构化",
         "useChat 自动管理会话状态，支持 React/Vue/Svelte",
         "tool 用 Zod 描述参数，embed 生成文本向量",
         "选择 SDK 取决于是否要全栈一体化（Vercel AI SDK 最省心）",
         "核心 API 命名清晰，后端生成/前端消费职责分明"],
    ),
    "### 2.2 后端：流式生成 + 工具调用": (
        "后端路由是 AI 能力的入口，负责调用模型、定义工具并以流式返回。",
        "streamText 接收 model/messages/tools，tools 由 tool() 定义（含 Zod 参数与 execute）；模型决定调用工具时 SDK 执行 execute 并把结果回灌继续生成，maxSteps 限制轮数；toDataStreamResponse 以 SSE 输出。",
        ["用 toDataStreamResponse() 暴露 SSE 流给前端 useChat",
         "工具 description 越清晰，模型越会正确调用",
         "maxSteps 允许多步推理（先查再算）",
         "工具 execute 需处理异常并返回可序列化结果",
         "后端只透传流，不缓冲完整响应以保低延迟"],
    ),
    "### 2.3 前端：useChat（Vue 3）": (
        "useChat 让前端以极少代码获得完整聊天交互能力。",
        "@ai-sdk/vue 的 useChat 内部维护 messages（含 role/content）、input、isLoading 等响应式状态，提交时 fetch 后端并增量解析流式响应自动追加到 messages。",
        ["解构 messages/input/handleInputChange/handleSubmit/isLoading 即可渲染",
         "initialMessages 可预设 system 或历史",
         "按 msg.role 区分用户/助手样式",
         "isLoading 用于禁用输入框",
         "api 指向后端 streamText 接口"],
    ),
    "### 2.4 结构化输出（streamObject）": (
        "让模型输出严格符合预设结构（JSON），便于程序消费。",
        "streamObject 接收 Zod schema 作为输出约束，生成被校验并序列化为对象；partialObjectStream 可在生成过程中逐步吐出“部分对象”，便于前端实时占位。",
        ["用 z.object 定义输出 schema，字段类型即约束",
         "嵌套结构（数组/对象）也支持",
         "partialObjectStream 适合边生成边渲染",
         "比手动 JSON.parse 更稳（避免格式破碎）",
         "可用于信息抽取、表单自动填充"],
    ),
    "### 3.1 核心组件": (
        "熟悉 LangChain.js 的组件体系，是组合复杂链与 Agent 的前提。",
        "LangChain 将 LLM 应用拆成可组合单元：模型（ChatOpenAI）、提示模板、链（RunnableSequence）、Agent 执行器、工具、记忆、切分器、向量库。",
        ["模型与提示模板解耦，便于复用与测试",
         "Runnable 接口让组件可 pipe 串联",
         "记忆组件负责多轮上下文",
         "切分器决定 RAG 检索粒度",
         "组件化使复杂流程可维护、可观测"],
    ),
    "### 3.2 LCEL 链式调用": (
        "LCEL 是 LangChain 推荐的声明式编排方式，比旧 AgentExecutor 更灵活。",
        "LCEL 通过 pipe（|）把 Prompt → Model → OutputParser 串成 RunnableSequence；每个节点实现统一 Runnable 接口（invoke/stream/batch），可运行时组合、并行、分支与回退。",
        ["prompt.pipe(model).pipe(parser) 即可形成链",
         "chain.invoke(input) 触发执行",
         "支持 stream 流式与 batch 批处理",
         "中间件式组合，易于插入自定义节点",
         "比字符串拼接更类型安全、易调试"],
    ),
    "### 3.3 Agent + 工具调用": (
        "Agent 让模型自主决定调用哪些工具完成多步任务。",
        "createReactAgent（LangGraph 预置）组合 LLM 与工具列表；运行时模型按 ReAct 思路“思考→调用工具→观察结果”循环，直到给出最终答案；DynamicTool 用 name/description/func 描述能力。",
        ["工具 description 是模型选择的关键",
         "func 必须是 async 且返回字符串",
         "避免用 eval 等危险实现（示例仅为演示）",
         "多工具组合可实现检索+计算+问答",
         "Agent 适合开放、多步骤任务，简单任务用普通链即可"],
    ),
    "### 3.4 RAG 完整实现": (
        "RAG 让模型基于私有/最新知识作答，缓解幻觉与知识截止。",
        "先把文档用 RecursiveCharacterTextSplitter 切成 chunk，用 OpenAIEmbeddings 向量化存入向量库；检索时把问题向量化，取 topK 相似 chunk 拼进提示词，再让模型据此生成答案。",
        ["chunkSize/chunkOverlap 影响检索召回与噪声",
         "embeddings 需与检索时同一模型",
         "asRetriever(k) 控制返回条数",
         "上下文拼接要注意 token 上限",
         "可加 rerank 提升相关性"],
    ),
    "### 4.1 基础调用": (
        "OpenAI Node SDK 是调用 GPT 的最底层封装，适合简单/定制场景。",
        "实例化 OpenAI 客户端（传 apiKey），调用 chat.completions.create 传入 model/messages（role 分 system/user/assistant），返回 choices[0].message.content；temperature 控制随机性。",
        ["messages 数组决定对话上下文",
         "system 消息设定人设与约束",
         "temperature 越高越发散",
         "用环境变量管理密钥，禁止硬编码",
         "适合直接、无框架需求的小调用"],
    ),
    "### 4.2 流式输出": (
        "流式让大模型“边生成边返回”，显著降低首字延迟、提升体验。",
        "create 时传 stream:true，返回异步可迭代流；逐块读取 chunk.choices[0].delta.content 并写入响应体（或前端 SSE），实现打字机效果。",
        ["stream:true 返回 AsyncIterable",
         "用 for await 逐块消费 delta.content",
         "空值需兜底（?.）",
         "后端常把流透传给前端避免缓冲",
         "与前端打字机/Markdown 渲染配合"],
    ),
    "### 4.3 工具调用（手动实现）": (
        "不依赖高级框架时，手工实现工具调用了解其底层机制。",
        "在请求中传 tools（function 定义含 name/description/parameters JSON Schema）；模型回复 message.tool_calls 时，本地解析 arguments、执行对应函数、把结果作为新消息回传模型继续生成。",
        ["tools 用 JSON Schema 描述参数",
         "需自检 tool_calls 是否存在再处理",
         "执行结果以 assistant+tool 消息回灌",
         "多轮循环可实现多步工具链",
         "比 SDK 封装更可控，但需自己管理状态"],
    ),
    "## 6.1 模型路由与 Fallback": (
        "模型路由与降级在成本、质量与可用性之间取得平衡。",
        "路由按任务复杂度选择模型（简单用 mini、复杂用旗舰、超复杂用 Claude 等）；Fallback 把模型排成降级链，前一个失败（异常/限流）自动切下一个，直到全部失败才报错。",
        ["按复杂度/语种/成本分级路由",
         "降级链按稳定性与成本排序（主→备）",
         "捕获异常后 continue 尝试下一模型",
         "记录失败模型便于告警",
         "可结合超时与限流策略"],
    ),
    "## 6.2 可观测性（LangSmith / Langfuse）": (
        "可观测性用于追踪、调试与优化生产中的 Agent 调用。",
        "LangSmith 通过环境变量开启自动追踪（记录每次 LLM/链的输入输出、延迟、token），也可手动 createRun 上报；Langfuse 提供开源自托管追踪；二者都能还原调用链路。",
        ["LANGCHAIN_TRACING_V2=true 开启自动追踪",
         "按 project 隔离不同环境",
         "手动 trace 记录输入/输出/错误/耗时",
         "关注 token 消耗与 P95 延迟",
         "生产环境必做，便于回归与成本控制"],
    ),
    "## 6.3 生产部署": (
        "部署形态决定延迟、成本与运维复杂度。",
        "边缘函数（Vercel Edge/Cloudflare Workers）在全球节点就近执行、低延迟，适合轻量流式接口；Node.js 服务与 Docker 提供完整生态与可控性，适合重计算与私有部署。",
        ["Vercel Edge 用 runtime='edge' 获得低延迟",
         "Cloudflare Workers 可绑定 AI 网关",
         "注意函数超时与冷启动限制",
         "重逻辑用 Node/Docker 自行运维",
         "流式响应需正确的 Content-Type（text/event-stream）"],
    ),
    "### Vercel Functions（Next.js / Nuxt）": (
        "Vercel Functions 是部署 AI 流式接口最省心的方式。",
        "在 route.ts 中导出 POST，内部调用 streamText 并以 toDataStreamResponse 返回；设置 runtime='edge' 可在边缘节点运行，缩短到用户的网络距离。",
        ["用 Next/Nuxt 约定路由暴露 /api/chat",
         "edge runtime 降低首字延迟",
         "需处理超时与区域限制",
         "配合 useChat 端到端流式",
         "适合托管、无需自建服务"],
    ),
    "### Cloudflare Workers": (
        "Cloudflare Workers 提供全球边缘运行与内置 AI 绑定。",
        "Worker 的 fetch 处理函数接收请求，可调用 env.AI.run 在边缘执行模型（如 Llama），并以 SSE 流式返回；部署在全球节点，就近低延迟。",
        ["用 env.AI.run 调用绑定模型",
         "流式返回需设 text/event-stream 头",
         "注意 CPU/冷启动限制",
         "适合轻量推理与网关",
         "与 R2/KV 结合可做无服务器 RAG"],
    ),
    "### 部署注意事项": (
        "选择部署平台需权衡延迟、限制与运维成本。",
        "各平台在运行时、超时、冷启动、生态上各有取舍：Vercel 易用但有函数超时，Cloudflare 全球边缘但 CPU 受限，Node/Docker 完全可控但需自运维。",
        ["Vercel 原生 Next/Nuxt，适合前端主导团队",
         "Cloudflare 适合全球低延迟与 AI 绑定",
         "Node 服务器生态完整",
         "Docker+K8s 可控但运维重",
         "按流量与合规选择"],
    ),
    "## 6.4 错误处理与重试": (
        "健壮的错误处理保障生产环境稳定性。",
        "对可恢复错误（429 限流、5xx 服务端）采用指数退避重试，对不可恢复错误（4xx 客户端）直接抛出；重试耗尽后降级或报错。",
        ["429 用 2^attempt 指数退避",
         "5xx 服务端错误重试",
         "4xx 不重试（参数错误）",
         "设最大重试次数防死循环",
         "可叠加超时与备用模型降级"],
    ),
}

new_lines, added = engine.expand(
    PATH,
    content_map,
    add_top_note=True,
    add_summary=False,
    summary_text="",
)
print("TS-Agent done. new_lines=%d added_blocks=%d" % (new_lines, added))
