# -*- coding: utf-8 -*-
import engine

PATH = "Vue3 AI Agent前端集成知识点系统梳理_优化版.md"

content_map = {
    "### 2.1 安装与配置": (
        "集成 Vercel AI SDK 到 Vue 3 项目的第一步。",
        "通过包管理器安装 ai（核心）、@ai-sdk/vue（Vue 适配钩子）、@ai-sdk/openai（OpenAI 提供商）；@ai-sdk/vue 提供 useChat/useCompletion 等 Vue 版组合式函数。",
        ["核心三包：ai + @ai-sdk/vue + 提供商",
         "也可用 @ai-sdk/anthropic 等换模型",
         "需 Vue 3 + Vite/打包环境",
         "后端需独立安装 ai 与提供商",
         "版本需互相兼容"],
    ),
    "### 2.2 useChat 核心用法": (
        "useChat 是 Vue 3 对话应用的入口钩子，封装消息/流/输入/错误等全部状态。",
        "useChat 返回 messages/input/handleInputChange/handleSubmit/isLoading/error/reload/stop/append/setMessages，内部用 fetch 调后端 SSE 接口并响应式更新；api/headers/body/initialMessages/onFinish/onError 可配置。",
        ["输入框用 :value+@input 绑定 handleInputChange（勿直接 v-model input）",
         "Enter 发送用 @keydown.enter.exact.prevent，Shift+Enter 换行",
         "setMessages([]) 清空对话",
         "reload 重发上一条，stop 中止生成",
         "onFinish/onError 做埋点与提示"],
    ),
    "### 3.1 自定义流式 Hook（不依赖 SDK）": (
        "不依赖官方 SDK 时，手写流式 Hook 理解 SSE 消费本质。",
        "用 fetch + AbortController 发请求，response.body.getReader() 逐块读取，TextDecoder 解码，按 SSE 的 data: 行解析 JSON 并累加到 AI 消息 content，驱动 Vue 响应式更新。",
        ["AbortController 支持 stop 中止",
         "reader.read() 循环直到 done",
         "SSE 行为 data: 前缀，[DONE] 结束",
         "解析失败要容错（try/catch）",
         "自行管理 messages/isLoading 响应式"],
    ),
    "### 3.2 打字机效果": (
        "打字机让历史/非流式文本也呈现逐字出现的效果，提升观感。",
        "监听文本变化，用 setInterval 按 speed 逐字符追加到 displayed，完成后清理定时器；组件卸载时也要清理避免内存泄漏。",
        ["从已显示长度续打，避免回退",
         "speed 控制每字间隔（如 20ms）",
         "onUnmounted 清理定时器",
         "可用 CSS 光标闪烁替代",
         "仅用于展示，不改动真实数据"],
    ),
    "### 4.1 markdown-it + highlight.js": (
        "把模型返回的 Markdown（含代码）渲染为带高亮的 HTML。",
        "markdown-it 解析 Markdown 为 HTML，highlight 选项接入 highlight.js 对代码块按语言高亮；html:false 禁止原始 HTML 防 XSS，渲染结果用 v-html 输出展示。",
        ["highlight 回调用 hljs.highlight 生成高亮 HTML",
         "html:false 防 XSS 注入",
         "引入 highlight.js 主题 CSS（如 github-dark）",
         "v-html 渲染需用可信内容（已禁 html）",
         "代码块可加行号/复制按钮"],
    ),
    "### 4.2 代码复制按钮": (
        "让用户一键复制 AI 回复中的代码，提升可用性。",
        "用 navigator.clipboard.writeText 复制代码文本，复制后短暂显示“已复制”反馈（setTimeout 复位）。",
        ["现代用 navigator.clipboard（需 HTTPS/localhost）",
         "复制成功给 2s 反馈",
         "需拿到代码文本（非渲染后 HTML）",
         "可放置于代码块右上角",
         "旧浏览器回退到 execCommand('copy')"],
    ),
    "### 5.1 工具调用状态展示": (
        "把模型触发的工具调用以可视化卡片呈现，让用户理解“AI 在做什么”。",
        "模型返回的消息携带 toolInvocations（含 toolName/args/state/result），前端按 state（call/result）展示调用中/已完成，并渲染参数与结果（JSON 格式化）。",
        ["用 toolCallId 作 key 稳定列表",
         "state='call' 显示“调用中”，'result' 显示结果",
         "参数用 JSON.stringify 美化",
         "可加图标/动画提升可读性",
         "异常结果要红色提示"],
    ),
    "### 5.2 人工确认工具（Human-in-the-loop）": (
        "对敏感/不可逆的工具调用（如发邮件、删数据）先让用户确认。",
        "当工具标记为需审批时，前端渲染确认卡片（参数+允许/拒绝按钮），emit approve/reject 事件，只有允许才真正执行。",
        ["危险操作必须人工确认",
         "展示完整参数便于判断",
         "approve/reject 回调驱动后端执行与否",
         "拒绝时给出降级回复",
         "结合权限与风控策略"],
    ),
    "### 6.1 Pinia 对话状态管理": (
        "用 Pinia 集中管理多会话、消息与持久化，避免组件间状态散落。",
        "定义 chat store，用 ref 维护 conversations 数组与 currentId，computed 取当前会话；并提供增删/保存/加载（localStorage）方法。",
        ["一个 Conversation 含 id/title/messages",
         "currentId 控制当前会话",
         "首条消息自动生成标题",
         "save/load 用 localStorage 持久化",
         "组合式 store 写法（setup 风格）"],
    ),
    "### 6.2 对话历史侧边栏": (
        "侧边栏提供新建/切换/删除会话的入口，是多会话 UI 的基础。",
        "遍历 chatStore.conversations 渲染列表，点击切换 currentId，新建调用 createConversation，删除调用 deleteConversation（.stop 阻止冒泡）。",
        ["高亮当前会话（active 类）",
         "新建按钮触发 createConversation",
         "删除用 @click.stop 防触发切换",
         "可显示时间/消息数",
         "移动端可折叠"],
    ),
    "## 6.3 WebSocket 实时通信": (
        "WebSocket 提供全双工实时通道，适合强实时对话与多端同步。",
        "建立 WebSocket 连接，onmessage 按自定义事件（token/done/tool_call）更新消息；onclose 时 3 秒后自动重连；send 推送用户消息。",
        ["token 事件累加流式内容",
         "done 事件结束并复位",
         "tool_call 事件插入工具调用卡片",
         "onclose 自动重连（指数退避更佳）",
         "组件卸载时 close 防泄漏"],
    ),
    "## 6.4 消息搜索与过滤": (
        "在长对话中快速定位历史消息，提升检索效率。",
        "用 computed 按 searchQuery 过滤当前会话消息（toLowerCase 包含匹配），highlight 用正则把匹配片段包成 <mark> 高亮。",
        ["computed 响应式过滤",
         "高亮前对查询做正则转义防注入",
         "用 v-html 渲染高亮（内容来自自身消息，风险低）",
         "可扩展为跨会话搜索",
         "空查询返回全部"],
    ),
    "## 6.5 键盘快捷键": (
        "键盘快捷键提升高频操作效率，接近专业工具体验。",
        "监听 window keydown，按 Ctrl/Cmd 组合键分发到 onSend/onNewChat/onFocusInput/onStop 等处理器，组件卸载时移除监听。",
        ["Ctrl/Cmd+Enter 发送",
         "Ctrl/Cmd+K 聚焦输入框",
         "Ctrl/Cmd+N 新对话",
         "Escape 停止生成",
         "onUnmounted 移除监听防泄漏"],
    ),
    "## 6.6 拖拽文件上传": (
        "拖拽/粘贴文件作为对话附件，支持多模态输入。",
        "监听 dragover/dragleave/drop 处理拖拽（dragleave 需判断 currentTarget===target 防误触），drop 读取 dataTransfer.files；paste 事件从 clipboardData 取图片；统一维护 attachedFiles 列表。",
        ["拖拽时加 drag-over 样式反馈",
         "用 currentTarget===target 判断真正离开",
         "粘贴图片从 clipboardData.items 取",
         "附件可预览与移除",
         "发送时随消息上传"],
    ),
    "### 7.1 虚拟滚动（长对话列表）": (
        "对话消息极多时，虚拟滚动只渲染可视区，保流畅。",
        "vue-virtual-scroller 的 DynamicScroller 按 min-item-size 与 size-dependencies（如 content 长度）动态计算可见项并复用 DOM，避免一次性渲染上千节点。",
        ["用 DynamicScroller + DynamicScrollerItem",
         "min-item-size 给估算高度",
         "size-dependencies 声明影响高度的因素以准确测量",
         "配合 MessageBubble 组件",
         "长列表性能关键手段"],
    ),
    "### 7.2 防抖输入与自动调整高度": (
        "提升输入框体验，自动撑高并避免频繁触发。",
        "autoResize 在输入时把 textarea 高度重置为 auto 再设为 scrollHeight（封顶），实现随内容增高；防抖用于搜索/联想类高频输入。",
        ["高度自动但设上限（如 200px）防溢出",
         "用 ref 指向 textarea",
         "防抖常用于消息搜索输入",
         "配合 Enter 发送逻辑",
         "不影响真实数据绑定"],
    ),
    "### 7.3 消息懒加载 Markdown": (
        "长消息的 Markdown 渲染开销大，懒渲染避免一次性卡顿。",
        "仅当消息进入视口（visible 为真）且尚未渲染时，才执行昂贵的 Markdown 渲染并缓存结果，避免对不可见消息做无用计算。",
        ["用 visible（如 IntersectionObserver/虚拟滚动）触发",
         "渲染结果缓存避免重复",
         "适合超长回复/代码密集内容",
         "配合虚拟滚动更佳",
         "注意切回时直接复用缓存"],
    ),
}

new_lines, added = engine.expand(
    PATH,
    content_map,
    add_top_note=True,
    add_summary=False,
    summary_text="",
)
print("Vue3-AI-Agent done. new_lines=%d added_blocks=%d" % (new_lines, added))
