# -*- coding: utf-8 -*-
import engine

PATH = "前端工程化知识点系统梳理_优化版.md"

content_map = {
    "### 2.1 模块化方案演进": (
        "了解模块化方案的演进，才能理解为什么 ES Module 成为今天的标准。",
        "早期用 IIFE 包裹避免全局污染；CommonJS 以同步 require 服务 Node；AMD/CMD 解决浏览器异步加载；最终 ES Module 由语言标准统一，支持静态分析与 Tree Shaking。",
        ["IIFE 用闭包隔离作用域，但仍需手动管理依赖",
         "CommonJS 同步加载，适合服务端，不适合浏览器并发",
         "AMD（RequireJS）异步按需加载，回调风格",
         "CMD（SeaJS）依赖就近、延迟执行",
         "ESM 是官方标准，浏览器与 Node 双端统一"],
    ),
    "### 3.1 Vite（推荐）": (
        "Vite 是当前最主流的前端构建/开发工具，显著提升开发体验与构建效率。",
        "开发期 Vite 不打包，直接用浏览器原生 ESM 加载源码、按需编译单文件，冷启动和 HMR 都极快；依赖预构建用 esbuild 把 CommonJS/多文件依赖转成 ESM。生产构建切换到 Rollup，借助 ESM 静态分析做更彻底的 Tree Shaking。",
        ["dev 基于原生 ESM，启动秒级",
         "HMR 精准更新变更模块，状态不丢失",
         "配置 alias 用 path.resolve 而非相对路径",
         "server.proxy 做开发跨域代理，changeOrigin 改 Host",
         "生产分包用 manualChunks/rollupOptions；环境变量用 import.meta.env"],
    ),
    "### 4.1 ESLint": (
        "ESLint 在编码阶段发现语法与潜在逻辑问题，统一团队的代码质量基线。",
        "ESLint 将源码解析为 AST，按规则遍历节点进行检测，可修复项通过 --fix 自动改写；规则来自 recommended 预设或插件（如 vue-eslint-parser），级别分 off/warn/error。",
        ["规则级别 off(0)/warn(1)/error(2)",
         "extends 继承共享配置，plugins 提供规则",
         "parser 指定语法解析器（Vue 用 vue-eslint-parser）",
         "与 Prettier 配合需 eslint-config-prettier 关掉格式冲突",
         "保存时自动 fix 提升效率；CI 中跑 eslint 拦截不合规代码"],
    ),
    "### 4.2 Prettier": (
        "Prettier 统一代码格式（缩进、引号、分号等），消除“格式之争”，让 Review 聚焦逻辑。",
        "Prettier 不分析语义，而是把代码重新打印为遵循统一风格的输出；它通过自带的解析器处理多语言，忽略原有排版，只保留语义。",
        ["关注格式而非质量，与 ESLint 职责互补",
         "常用配置：semi/singleQuote/tabWidth/printWidth/trailingComma",
         ".prettierignore 排除不需格式化的文件",
         "用 eslint-plugin-prettier 将格式错误升级为 ESLint 报错",
         "编辑器保存时自动 prettier --write"],
    ),
    "### 5.1 Husky": (
        "Husky 把 Git 钩子接入前端工具链，在提交/推送等关键节点自动执行检查。",
        "Husky 在 .husky/ 目录生成钩子脚本，Git 在对应事件（pre-commit、commit-msg、pre-push 等）触发时执行它们；通过 npm prepare 脚本在安装依赖后自动启用。",
        ["pre-commit 在提交前触发，可拦截不合格代码",
         "commit-msg 校验提交信息格式",
         "常与 lint-staged 配合只对暂存文件检查",
         "husky install 需在 prepare 中执行以保证克隆后生效",
         "钩子失败会让 Git 操作中断，强制修复"],
    ),
    "### 5.2 lint-staged": (
        "lint-staged 只对本次提交（暂存区）的文件跑检查，避免全量 lint 拖慢提交。",
        "Git 提交时，lint-staged 取出 git add 的文件列表，按配置对其运行 ESLint/Prettier 等命令并自动写回修复结果，再继续提交流程。",
        ["只处理暂存文件，速度远快于全量检查",
         "配置按文件后缀匹配命令（js/ts/vue、css、md）",
         "常与 pre-commit 钩子联动",
         "自动 --fix/--write 会在提交前就地修改文件",
         "大仓库必备，显著提升提交体验"],
    ),
    "### 6.1 GitHub Actions 示例": (
        "GitHub Actions 是托管式 CI/CD，能在 push/PR 时自动跑测试、构建与部署。",
        "工作流由仓库内 .github/workflows 的 YAML 定义，包含触发事件（on）与若干 job；每个 job 在独立 runner 虚拟机中按顺序执行 steps（checkout、装环境、跑脚本等）。",
        ["on 指定触发事件（push/pr）与分支",
         "actions/checkout 拉代码，setup-node 配 Node 版本",
         "用 cache 缓存依赖（node_modules）加速",
         "npm ci 按 lockfile 精确安装，比 npm install 更适合 CI",
         "upload-artifact 留存构建产物供部署使用"],
    ),
    "### 8.1 单元测试（Vitest / Jest）": (
        "单元测试验证最小代码单元（函数/模块）的正确性，是质量保障的第一道防线。",
        "测试框架提供 describe/it/expect 组织用例与断言，运行器在隔离环境执行并通过断言判断通过/失败；Vitest 基于 Vite 生态、原生 ESM、速度快，Jest 生态成熟、自带 mock。",
        ["用例三件套：分组 describe、单测 it、断言 expect",
         "纯函数测试最直接，重点覆盖边界与异常",
         "Vitest 兼容 Jest API，迁移成本低",
         "用 mock 隔离外部依赖（定时器、请求）",
         "配合覆盖率（coverage）衡量测试完整性"],
    ),
    "### 8.2 组件测试（Vue Test Utils）": (
        "组件测试验证 UI 组件的行为（渲染、交互、事件发射），弥补单元测试对视图的盲区。",
        "@vue/test-utils 的 mount/shallowMount 把组件挂载到测试环境，返回 wrapper，可查询 DOM、触发事件、断言 props/emitted，配合 Vitest/Jest 运行。",
        ["mount 渲染完整子树，shallowMount 只渲染当前组件（子组件打桩）",
         "wrapper.find 定位元素，trigger 模拟交互",
         "用 emitted() 断言组件抛出的事件",
         "props/data 可在挂载时注入以覆盖场景",
         "关注交互结果而非内部实现，降低脆弱性"],
    ),
    "### 8.3 E2E 测试（Cypress / Playwright）": (
        "E2E 测试模拟真实用户在浏览器中走通完整业务流程，保障端到端可用性。",
        "E2E 框架启动真实/无头浏览器，按脚本访问页面、操作元素、断言结果；Cypress 自带交互式 runner，Playwright 支持多浏览器与并行，均通过选择器定位元素。",
        ["站在用户视角验证关键链路（如登录、下单）",
         "用稳定选择器（data-testid）而非易变的样式/文本",
         "命令链式调用，自动等待元素可交互",
         "需起服务/数据库等完整环境，成本高、跑得慢",
         "与单元/组件测试分层，E2E 只覆盖最核心路径"],
    ),
    "### 7.1 构建性能": (
        "构建性能决定开发期启动速度与 CI 构建耗时，影响团队日常效率。",
        "构建工具把源码编译打包，瓶颈在依赖图解析与转换；Vite 开发期免打包、按需编译所以快，Webpack 可借缓存与多线程 loader 提速，合理配置 alias/externals 减少搜索与打包范围。",
        ["Vite 开发期天然快，Webpack 用 cache-loader/thread-loader 并行与缓存",
         "配置 alias 缩短模块解析路径",
         "externals 把不变的大依赖排除出打包",
         "生产构建用持久化缓存（Vite 的 node_modules/.vite）",
         "DLL 预打包（Webpack 旧方案）已被 Vite 预构建取代；CI 中缓存依赖与构建产物"],
    ),
    "### 7.2 加载性能": (
        "加载性能直接决定用户的首屏等待与留存，是前端性能优化的核心战场。",
        "加载优化围绕“减少请求数、减小资源体积、利用缓存与并行”展开：代码分割按需加载、Tree Shaking 删死代码、图片用现代格式与懒加载、Gzip/Brotli 压缩、CDN 就近分发、HTTP 缓存避免重复请求、preload/prefetch 提前获取关键资源。",
        ["路由懒加载是最有效的代码分割手段",
         "Tree Shaking 依赖 ESM 静态分析，移除未使用导出",
         "图片用 WebP/AVIF 并 loading=\"lazy\"",
         "开启 Gzip/Brotli 与 CDN 加速静态资源",
         "强缓存（Cache-Control）+ 协商缓存（ETag）配合 hash 文件名；preload 关键资源、prefetch 预测资源"],
    ),
}

new_lines, added = engine.expand(
    PATH,
    content_map,
    add_top_note=True,
    add_summary=False,
    summary_text="",
)
print("FE done. new_lines=%d added_blocks=%d" % (new_lines, added))
